app #01

diff --git a/.github/workflows/git.yaml b/.github/workflows/git.yaml
--- a/.github/workflows/git.yaml
+++ b/.github/workflows/git.yaml
@@ -24,7 +24,7 @@ jobs:
       - name: Set up build environment
         run: |
           sudo apt-get update
-          sudo apt-get install -y cmake build-essential sqlite3 libsqlite3-dev uuid-dev mingw-w64 
+          sudo apt-get install -y cmake build-essential gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 make sqlite3 libsqlite3-dev uuid-dev mingw-w64 
           sudo apt-get install -y mingw-w64-x86-64-dev uuid-dev
 
       - name: Download and build SQLite for Windows
@@ -62,22 +62,22 @@ jobs:
           fi
 
       # Compilar para Windows usando MinGW
-      # - name: Build for Windows
-      #   run: |
-      #     cd src
-      #     make clean
-      #     make CC=x86_64-w64-mingw32-gcc  # Compila com MinGW para Windows
+      - name: Build for Windows
+        run: |
+          cd src
+          make clean
+          make CC=x86_64-w64-mingw32-gcc  # Compila com MinGW para Windows
 
-      # - name: Package Windows Binary
-      #   run: |
-      #     if [ -f ./src/StockManager.exe ]; then
-      #       cd src
-      #       zip StockManager-windows.zip StockManager.exe
-      #       echo "STOCKMANAGER_WINDOWS_PACKAGE=src/StockManager-windows.zip" >> $GITHUB_ENV
-      #     else
-      #       echo "Windows binary not found!" >&2
-      #       exit 1
-      #     fi
+      - name: Package Windows Binary
+        run: |
+          if [ -f ./src/StockManager.exe ]; then
+            cd src
+            zip StockManager-windows.zip StockManager.exe
+            echo "STOCKMANAGER_WINDOWS_PACKAGE=src/StockManager-windows.zip" >> $GITHUB_ENV
+          else
+            echo "Windows binary not found!" >&2
+            exit 1
+          fi
 
       # Upload dos binários como artefatos
       - name: Upload Linux Binary as artifact
@@ -86,11 +86,11 @@ jobs:
           name: StockManager-linux
           path: ${{ env.STOCKMANAGER_LINUX_PACKAGE }}
 
-      # - name: Upload Windows Binary as artifact
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: StockManager-windows
-      #     path: ${{ env.STOCKMANAGER_WINDOWS_PACKAGE }}
+      - name: Upload Windows Binary as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: StockManager-windows
+          path: ${{ env.STOCKMANAGER_WINDOWS_PACKAGE }}
 
   release:
     runs-on: ubuntu-latest
@@ -119,10 +119,10 @@ jobs:
           asset_name: StockManager-linux.tar.gz
           asset_content_type: application/gzip
 
-      # - name: Upload Windows Release Asset
-      #   uses: actions/upload-release-asset@v1
-      #   with:
-      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #     asset_path: ${{ env.STOCKMANAGER_WINDOWS_PACKAGE }}
-      #     asset_name: StockManager-windows.zip
-      #     asset_content_type: application/zip
+      - name: Upload Windows Release Asset
+        uses: actions/upload-release-asset@v1
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ env.STOCKMANAGER_WINDOWS_PACKAGE }}
+          asset_name: StockManager-windows.zip
+          asset_content_type: application/zip
