app #1

diff --git a/.github/workflows/linux.yaml b/.github/workflows/linux.yaml
--- a/.github/workflows/linux.yaml
+++ b/.github/workflows/linux.yaml
@@ -1,77 +1,77 @@
-name: Build project C for Linux
+# name: Build project C for Linux
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - main
 
-permissions:
-  contents: write
-  deployments: write
+# permissions:
+#   contents: write
+#   deployments: write
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     timeout-minutes: 30
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      - name: Set up build environment
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y build-essential libsqlite3-dev uuid-dev 
+#       - name: Set up build environment
+#         run: |
+#           sudo apt-get update
+#           sudo apt-get install -y build-essential libsqlite3-dev uuid-dev 
 
-      - name: Build with GCC
-        run: |
-          cd src
-          make clean
-          make CC=gcc  # Apenas GCC é utilizado
+#       - name: Build with GCC
+#         run: |
+#           cd src
+#           make clean
+#           make CC=gcc  # Apenas GCC é utilizado
 
-      - name: Package Binaries
-        run: |
-          # Verifica se o binário foi criado e empacota
-          if [ -f ./StockManager ]; then
-            cd src  # Certifique-se de estar no diretório correto
-            tar -czvf StockManager-linux.tar.gz StockManager
-            echo "STOCKMANAGER_PACKAGE=StockManager-linux.tar.gz" >> $GITHUB_ENV
-          else
-            echo "StockManager binary not found!" >&2
-            exit 1
-          fi
+#       - name: Package Binaries
+#         run: |
+#           # Verifica se o binário foi criado e empacota
+#           if [ -f ./StockManager ]; then
+#             cd src  # Certifique-se de estar no diretório correto
+#             tar -czvf StockManager-linux.tar.gz StockManager
+#             echo "STOCKMANAGER_PACKAGE=StockManager-linux.tar.gz" >> $GITHUB_ENV
+#           else
+#             echo "StockManager binary not found!" >&2
+#             exit 1
+#           fi
 
-      - name: Upload binaries as artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: Binaries-linux-gcc
-          path: src/StockManager-linux.tar.gz
+#       - name: Upload binaries as artifacts
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: Binaries-linux-gcc
+#           path: src/StockManager-linux.tar.gz
 
-  release:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+#   release:
+#     runs-on: ubuntu-latest
+#     needs: build
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      - name: Create GitHub Release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: v1.0.0-${{ github.run_number }}  # Exemplo de tag dinâmica
-          release_name: "Release v1.0.0"
-          draft: false
-          prerelease: false
+#       - name: Create GitHub Release
+#         id: create_release
+#         uses: actions/create-release@v1
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#         with:
+#           tag_name: v1.0.0-${{ github.run_number }}  # Exemplo de tag dinâmica
+#           release_name: "Release v1.0.0"
+#           draft: false
+#           prerelease: false
 
-      - name: Upload Linux Release Asset
-        uses: actions/upload-release-asset@v1
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: StockManager-linux.tar.gz  # Verifique se esse caminho é correto
-          asset_name: StockManager-linux.tar.gz
-          asset_content_type: application/gzip
+#       - name: Upload Linux Release Asset
+#         uses: actions/upload-release-asset@v1
+#         with:
+#           upload_url: ${{ steps.create_release.outputs.upload_url }}
+#           asset_path: StockManager-linux.tar.gz  # Verifique se esse caminho é correto
+#           asset_name: StockManager-linux.tar.gz
+#           asset_content_type: application/gzip
