app #01

diff --git a/.github/workflows/windows.yaml b/.github/workflows/windows.yaml
--- a/.github/workflows/windows.yaml
+++ b/.github/workflows/windows.yaml
@@ -1,77 +1,77 @@
-# name: Build project C for Windows
+name: Build project C for Windows
 
-# on:
-#   push:
-#     branches:
-#       - main
-#   pull_request:
-#     branches:
-#       - main
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
-# permissions:
-#   contents: write
-#   deployments: write
+permissions:
+  contents: write
+  deployments: write
 
-# jobs:
-#   build:
-#     runs-on: windows-latest
-#     timeout-minutes: 30
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v3
+jobs:
+  build:
+    runs-on: windows-latest
+    timeout-minutes: 30
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-#       - name: Install dependencies using Chocolatey
-#         run: |
-#           choco install gcc
-#           choco install make
-#           choco install sqlite
-#           choco install uuid
-#           choco install boost
+      - name: Install dependencies using Chocolatey
+        run: |
+          choco install gcc
+          choco install make
+          choco install sqlite
+          choco install uuid
+          choco install boost
 
-#       - name: Build with GCC
-#         run: |
-#           cd src
-#           make clean
-#           make CC=gcc CFLAGS="-I/installed/x64-windows/include" LDFLAGS="-L/usr/lib -lsqlite3 -lboost_system"
+      - name: Build with GCC
+        run: |
+          cd src
+          make clean
+          make CC=gcc CFLAGS="-I/installed/x64-windows/include" LDFLAGS="-L/usr/lib -lsqlite3 -lboost_system"
 
-#       - name: Package Binaries
-#         run: |
-#           if [ -f ./src/StockManager.exe ]; then
-#             powershell -Command "Compress-Archive -Path .\src\StockManager.exe -DestinationPath StockManager-windows.zip"
-#             echo "STOCKMANAGER_PACKAGE=StockManager-windows.zip" >> $GITHUB_ENV
-#           else
-#             echo "StockManager.exe binary not found!" >&2
-#             exit 1
-#           fi
+      - name: Package Binaries
+        run: |
+          if [ -f ./src/StockManager.exe ]; then
+            powershell -Command "Compress-Archive -Path .\src\StockManager.exe -DestinationPath StockManager-windows.zip"
+            echo "STOCKMANAGER_PACKAGE=StockManager-windows.zip" >> $GITHUB_ENV
+          else
+            echo "StockManager.exe binary not found!" >&2
+            exit 1
+          fi
 
-#       - name: Upload binaries as artifacts
-#         uses: actions/upload-artifact@v3
-#         with:
-#           name: Binaries-windows-gcc
-#           path: ${{ env.STOCKMANAGER_PACKAGE }}
+      - name: Upload binaries as artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: Binaries-windows-gcc
+          path: ${{ env.STOCKMANAGER_PACKAGE }}
 
-#   release:
-#     runs-on: ubuntu-latest
-#     needs: build
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v3
+  release:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-#       - name: Create GitHub Release
-#         id: create_release
-#         uses: actions/create-release@v1
-#         env:
-#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#         with:
-#           tag_name: v1.0.0  # Considere tornar isso dinâmico
-#           release_name: "Release v1.0.0"
-#           draft: false
-#           prerelease: false
+      - name: Create GitHub Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: v1.0.0  # Considere tornar isso dinâmico
+          release_name: "Release v1.0.0"
+          draft: false
+          prerelease: false
 
-#       - name: Upload Windows Release Asset
-#         uses: actions/upload-release-asset@v1
-#         with:
-#           upload_url: ${{ steps.create_release.outputs.upload_url }}
-#           asset_path: ${{ env.STOCKMANAGER_PACKAGE }}
-#           asset_name: StockManager-windows.zip  
-#           asset_content_type: application/zip
+      - name: Upload Windows Release Asset
+        uses: actions/upload-release-asset@v1
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ env.STOCKMANAGER_PACKAGE }}
+          asset_name: StockManager-windows.zip  
+          asset_content_type: application/zip
